### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by AndreasEdal** [nicni19/CookMate#2]
Implementing an AuthenticationService that can authenticate and answer if the users is authorized to get data.
Create the sign in screen:
![image](https://user-images.githubusercontent.com/55428257/139101765-a91ac981-bf96-49dc-83f5-0fc5ed363ea7.png)

Create the sign up screen:
![image](https://user-images.githubusercontent.com/55428257/139101882-3a3e18f0-da89-41e3-b04e-bc57edc190d7.png)

**Comment by reWach** [comment]
I've implemented Sign In and Sign Up screen. Currently the forms just need  styling and to call AuthenticationService onSubmit once AuthenticationService has been implemented. (currently: Navigation branch)

**Comment by reWach** [comment]
* You are now able to sign in using a registered User
* You are now able to sign out
* You can access the signed in User using AuthContext
* The User/User session is stored in AsyncStorage (native version of local storage). Session currently includes User's id, first name and last name.
