### ISSUE TITLE
Create recipe

### ISSUE THREAD

**Issue by AndreasEdal** [nicni19/CookMate#3]
Implement the create recipe user story:

This is a longer one. 
* create the functionality as in the hifi model
* when done the recipe should be saved in the persistence layer

Challenges:
* The image picker is maybe a bit hard to implement by hand. Maybe there are libraries we can use?

![image](https://user-images.githubusercontent.com/55428257/139102111-daa7806b-d0b6-48ed-a2aa-d45303860889.png)

**Comment by reWach** [comment]
Missing styling of components, and small features such as numbering of instructions, deleting, and editing of added instructions & ingredients in the lists.

**Comment by reWach** [comment]
Done
